import os

BACKEND_DOWNLOAD_DIRECTORY = os.environ["BACKEND_DOWNLOAD_DIRECTORY"]
BACKEND_ERROR_DIRECTORY = os.environ["BACKEND_ERROR_DIRECTORY"]
BACKEND_PROCESSED_DIRECTORY = os.environ["BACKEND_PROCESSED_DIRECTORY"]
