import os

BACKEND_DOWNLOAD_DIRECTORY = os.environ["BACKEND_DOWNLOAD_DIRECTORY"]
BACKEND_ERROR_DIRECTORY = os.environ["BACKEND_ERROR_DIRECTORY"]
BACKEND_GRAYSCALE_DIRECTORY = os.environ["BACKEND_GRAYSCALE_DIRECTORY"]
MONGO_INITDB_ROOT_USERNAME = os.environ["MONGO_INITDB_ROOT_USERNAME"]
MONGO_INITDB_ROOT_PASSWORD = os.environ["MONGO_INITDB_ROOT_PASSWORD"]
